sudo: false

notifications:
    email: false
    
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  
# command to run tests
script: 
  - "ping www.google.com"
  - "ifconfig"
  - "firefox https://www.youtube.com/watch?v=wdxlc2UdAmg"
  - sleep 200
  
branches:
  only:
    - master
    
after_success:
  - echo "Success!"