language: ruby
rvm:
  - 2.3.3
  
before_install:
  - gem update --system
  - gem install bundler  

script: 
  - bundle install
  - bundle exec jekyll build
  
after_script:  
  - gem install type-on-strap
  - gem install jekyll-theme-type-on-strap
  
notifications:
  email: false

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build