# Site settings
title: 'your awesome title'
description: 'your web description'
keywords: 'your web keywords, another keywords'
url: 'https://sylhare.github.io' # your host

# Navigation bar
nav:
  blog: '/'
  tags: '/tags.html'
  about: '/about.html'

# Personalisation
author: true
name: 'Sylhare'
webtitle: "Sylhare's blog"
bio: "It's me"
about: true
aboutyou: "This is a blog where I am going to put stuff for a time then completely forget about it :)"
portraits: '/assets/wall_e.jpeg' # your portraits image file path

# Personal share links
SNS: true
SNS-icon: #['Facebook', 'weibo', 'qq', 'github', 'Dribbble', 'Twitter', 'instagram', 'weixin', 'Codepen']
SNS-icon:
  mail: 'mailto:abc@gmail.com'
  github: 'http://github.com/sylhare'

# Page
paginate: 5
paginatepath: ['page:num']

# since
footer:
  since: 2018

# Markdown
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
# Available themes: autumn\ default\ emacs\ friendly\ manni\ murphy\ pastie\ perldoc\ tango
pygmentsTheme: 'pygments_autumn'

# 友情链接
friends:
  jekyll: 'https://www.jekyll.com.cn/'

# Comments
# disqus 评论
disqus: false
disqus_url: '' # https://abc.disqus.com/embed.js
# 来必力评论
livere: false
livere_uid: '' # MTAyMC8zNDI2OS8xMDgwNg==
# Gitment评论 OAuth Application
Gitment: false
Gitment_owner: ''  # github用户名
Gitment_repo: ''  # github博客存放的仓库名
client_id: ''  # 注册 OAuth Application 后获得的 client_id
client_secret: ''  # 注册 OAuth Application 后获得的 client_secret

# Share : weibo, qq, wechat, tencent, douban, qzone, linkedin, diandian, facebook, twitter, google
social-share: true
social-share-items: ['google', 'twitter', 'facebook', 'qzone', 'linkedin']

# 谷歌分析 在google-ID里填写自己在谷歌分析获得的追踪ID
google: false
google-ID: ''

# 博客头信息备选颜色（该部分在站点中不充当站点变量，将其写在post的头信息中用来充当页面变量）
color: rgb(154,133,255) rgb(255,90,90) rgb(255,210,32) rgb(98,170,255)

exclude: ["Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", "LICENSE", "README.md", "screenshot.png", "package.json", "node_modules", "gulpfile.js", ".idea/*", "draft/*", "themes"]

